import os
import sys
from random import randint
with open('theatres.txt') as f:
	for line in f:
		for i in range(1,30):
			print("INSERT INTO `arrange` (`ArrangeId`, `Showtime`, `Location`, `Name`, `SeatsLeft`) VALUES (NULL, '2019-{}-{} {}:00:00', (SELECT Location from theater WHERE Location LIKE '%{}%'), (SELECT Name from movie WHERE Name LIKE '%TOY STORY 4%'), '300');".format(randint(7,12), i, randint(9,21), line.split(";")[1].strip()))
			print("INSERT INTO `arrange` (`ArrangeId`, `Showtime`, `Location`, `Name`, `SeatsLeft`) VALUES (NULL, '2019-{}-{} {}:00:00', (SELECT Location from theater WHERE Location LIKE '%{}%'), (SELECT Name from movie WHERE Name LIKE '%SPIDER-MAN: FAR FROM HOME (2019)%'), '300');".format(randint(7,12), i, randint(9,21),line.split(";")[1].strip()))
			print("INSERT INTO `arrange` (`ArrangeId`, `Showtime`, `Location`, `Name`, `SeatsLeft`) VALUES (NULL, '2019-{}-{} {}:00:00', (SELECT Location from theater WHERE Location LIKE '%{}%'), (SELECT Name from movie WHERE Name LIKE '%THE SECRET LIFE OF PETS 2%'), '300');".format(randint(7,12), i, randint(9,21),line.split(";")[1].strip()))
			print("INSERT INTO `arrange` (`ArrangeId`, `Showtime`, `Location`, `Name`, `SeatsLeft`) VALUES (NULL, '2019-{}-{} {}:00:00', (SELECT Location from theater WHERE Location LIKE '%{}%'), (SELECT Name from movie WHERE Name LIKE '%AVENGERS: ENDGAME (2019)%'), '300');".format(randint(7,12), i, randint(9,21),line.split(";")[1].strip()))
			print("INSERT INTO `arrange` (`ArrangeId`, `Showtime`, `Location`, `Name`, `SeatsLeft`) VALUES (NULL, '2019-{}-{} {}:00:00', (SELECT Location from theater WHERE Location LIKE '%{}%'), (SELECT Name from movie WHERE Name LIKE '%POKÉMON DETECTIVE PIKACHU%'), '300');".format(randint(7,12), i, randint(9,21),line.split(";")[1].strip()))
			print("INSERT INTO `arrange` (`ArrangeId`, `Showtime`, `Location`, `Name`, `SeatsLeft`) VALUES (NULL, '2019-{}-{} {}:00:00', (SELECT Location from theater WHERE Location LIKE '%{}%'), (SELECT Name from movie WHERE Name LIKE '%ANNABELLE COMES HOME%'), '300');".format(randint(7,12), i, randint(9,21), line.split(";")[1].strip()))
			print("INSERT INTO `arrange` (`ArrangeId`, `Showtime`, `Location`, `Name`, `SeatsLeft`) VALUES (NULL, '2019-{}-{} {}:00:00', (SELECT Location from theater WHERE Location LIKE '%{}%'), (SELECT Name from movie WHERE Name LIKE '%YESTERDAY (2019)%'), '300');".format(randint(7,12), i, randint(9,21), line.split(";")[1].strip()))